version: '3'

networks:
    davids-network:

services:
    nginx:
        image: nginx:latest
        container_name: web
        volumes:
            - ./logs:/var/log/nginx/
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./laravel:/var/wwww/html/public;
        ports:
            - 80:80
        networks:
            - davids-network
        depends_on: 
            - php
            - mysql
    
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: xxxxxx
            MYSQL_DATABASE: xxxxxx
            MYSQL_USER: xxxxxx
            MYSQL_PASSWORD: xxxxxx
        networks:
            - davids-network
        
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./laravel:/var/www/html
        networks:
            - davids-network
